GET http://localhost:7125/api/book/admin/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlZjQ5ODAyYS00NzEzLTRhNDktODdjMy04YjBjZmUwOGE5MzciLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTczNzU0MTIzNSwiZXhwIjoxNzM3NTQ0ODM1LCJpYXQiOjE3Mzc1NDEyMzUsImlzcyI6IkVMaWJyYXJ5LkFQSSIsImF1ZCI6IkVMaWJyYXJ5LkNsaWVudCJ9.wZ1_qGJrsK51KNIbfwYCMQGl-1NXWGE1gRHFHWDrH6Q